name: CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ vars.DOCKER_IMAGE }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy through SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo podman pull ${{ vars.DOCKER_IMAGE }}
            sudo podman pod create \
              -p ${{ vars.DEPLOY_PORT }}:8000 \
              --replace ${{ vars.DEPLOY_POD }}
            sudo podman run -d \
              --name ${{ vars.DEPLOY_CONTAINER }}-postgres \
              --pod ${{ vars.DEPLOY_POD }} \
              -e POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -v ${{ vars.DEPLOY_CONTAINER }}-postgres:/var/lib/postgresql/data \
              --replace --restart always postgres:17.2-alpine
            sudo podman run -d \
              --name ${{ vars.DEPLOY_CONTAINER }} \
              --pod ${{ vars.DEPLOY_POD }} \
              -e OPENAI_KEY=${{ secrets.OPENAI_KEY }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              --replace --restart always ${{ vars.DOCKER_IMAGE }}
